// 自动生成（bash scripts/gen-sidebar.sh）。章→节嵌套侧边栏；
// 节标题取自各章目录页 chXX.md 的 [N.M 标题](./chXX_N.md) 链接文本。
import type { SidebarItem } from 'vitepress'

export const sidebar: SidebarItem[] = [
  {
    text: '起步：能量、效率与开关',
    collapsed: false,
    items: [
      {
        text: '第 1 章 能量变换的艺术与代价',
        collapsed: true,
        items: [
          { text: '章节概览', link: '/power-electronics/ch01' },
          { text: '1.1 电力处理的本质：开关的魔力', link: '/power-electronics/ch01_1' },
          { text: '1.2 电力电子技术的几个应用场景', link: '/power-electronics/ch01_2' },
          { text: '1.3 电力电子技术的核心要素', link: '/power-electronics/ch01_3' },
        ],
      },
      {
        text: '第 2 章 稳态变换器分析原理',
        collapsed: true,
        items: [
          { text: '章节概览', link: '/power-electronics/ch02' },
          { text: '2.1 开关、纹波与那个被我们藏起来的直流分量', link: '/power-electronics/ch02_1' },
          { text: '2.2 伏秒平衡与电荷平衡：那个藏在波形里的“小纹波”秘密', link: '/power-electronics/ch02_2' },
          { text: '2.3 Boost 变换器实战', link: '/power-electronics/ch02_3' },
          { text: '2.5 估算包含双极点低通滤波器的变换器输出电压纹波', link: '/power-electronics/ch02_4' },
          { text: '2.6 章节总结与关键点回顾', link: '/power-electronics/ch02_5' },
          { text: '习题：稳态变换器分析实战', link: '/power-electronics/ch02_6' },
        ],
      },
      {
        text: '第 3 章 稳态等效电路建模：损耗与效率',
        collapsed: true,
        items: [
          { text: '章节概览', link: '/power-electronics/ch03' },
          { text: '3.1 DC 变压器模型', link: '/power-electronics/ch03_1' },
          { text: '3.2 把电感损耗找回来', link: '/power-electronics/ch03_2' },
          { text: '3.3 构建等效电路模型', link: '/power-electronics/ch03_3' },
          { text: '3.4 怎么搞定模型的输入端口', link: '/power-electronics/ch03_4' },
          { text: '3.5 在 Boost 模型中计入半导体导通损耗', link: '/power-electronics/ch03_5' },
          { text: '3.6 习题：损耗与效率', link: '/power-electronics/ch03_6' },
        ],
      },
      {
        text: '第 4 章 当理想开关遇到物理现实',
        collapsed: true,
        items: [
          { text: '章节概览', link: '/power-electronics/ch04' },
          { text: '4.1  开关应用', link: '/power-electronics/ch04_1' },
          { text: '4.2  功率半导体器件导论', link: '/power-electronics/ch04_2' },
          { text: '4.3.1  深入功率二极管：关于"慢"的物理学', link: '/power-electronics/ch04_3' },
          { text: '4.3.2  讨论：二极管的"身材"管理与选型哲学', link: '/power-electronics/ch04_4' },
          { text: '4.3.3  建模二极管引起的开关损耗', link: '/power-electronics/ch04_5' },
          { text: '4.3.4  Boost 变换器实例：把损耗装进模型', link: '/power-electronics/ch04_6' },
          { text: '4.4  金属-氧化物-半导体场效应晶体管 (MOSFET)', link: '/power-electronics/ch04_7' },
          { text: '4.5  少子型双极型晶体管', link: '/power-electronics/ch04_8' },
          { text: '4.6  额外的开关损耗源', link: '/power-electronics/ch04_9' },
          { text: '4.7  核心要点回顾', link: '/power-electronics/ch04_10' },
          { text: '4.8  习题', link: '/power-electronics/ch04_11' },
        ],
      },
      {
        text: '第 5 章 当波形不再连续',
        collapsed: true,
        items: [
          { text: '章节概览', link: '/power-electronics/ch05' },
          { text: '5.1 断流是怎么发生的：寻找 CCM/DCM 的边界', link: '/power-electronics/ch05_1' },
          { text: '5.2 转换比 M(D, K) 的解析', link: '/power-electronics/ch05_2' },
          { text: '5.3 实战演练：Boost 变换器', link: '/power-electronics/ch05_3' },
          { text: '5.4 练习与实战', link: '/power-electronics/ch05_4' },
        ],
      },
    ],
  },
  {
    text: '变换器电路与建模',
    collapsed: false,
    items: [
      {
        text: '第 6 章 变换器电路',
        collapsed: true,
        items: [
          { text: '章节概览', link: '/power-electronics/ch06' },
          { text: '6.1 电路操纵术：从 Buck 推导出整个家族', link: '/power-electronics/ch06_1' },
          { text: '6.2 变换器家族清单', link: '/power-electronics/ch06_2' },
          { text: '6.3.1 全桥与半桥隔离型 Buck 变换器', link: '/power-electronics/ch06_3' },
          { text: '6.3.2 正激变换器', link: '/power-electronics/ch06_4' },
          { text: '6.3.4 反激变换器', link: '/power-electronics/ch06_5' },
          { text: '6.3.5 Boost 派生隔离变换器', link: '/power-electronics/ch06_6' },
          { text: '6.3.6 SEPIC 和 Ćuk 变换器的隔离版', link: '/power-electronics/ch06_7' },
          { text: '6.8 习题', link: '/power-electronics/ch06_8' },
        ],
      },
      {
        text: '第 7 章 交流等效电路建模',
        collapsed: true,
        items: [
          { text: '章节概览', link: '/power-electronics/ch07' },
          { text: '7.1 镜子与幽灵：当变换器开始动起来', link: '/power-electronics/ch07_1' },
          { text: '7.2.3 关于平均化近似的讨论 / 平均化电容波形 / 平均输入电流', link: '/power-electronics/ch07_2' },
          { text: '7.2.6 扰动与线性化', link: '/power-electronics/ch07_3' },
          { text: '7.2.7 构建小信号等效电路模型', link: '/power-electronics/ch07_4' },
          { text: '7.2.10 示例：考虑寄生电阻的反激变换器', link: '/power-electronics/ch07_5' },
          { text: '7.3 建模脉宽调制器（PWM）', link: '/power-electronics/ch07_6' },
          { text: '7.4 标准电路模型', link: '/power-electronics/ch07_7' },
          { text: '7.5.1 网络的状态方程', link: '/power-electronics/ch07_8' },
          { text: '7.5.3 深入理解状态空间平均法的结果', link: '/power-electronics/ch07_9' },
          { text: '7.5.4 示例：非理想 Buck–Boost 变换器的状态空间平均', link: '/power-electronics/ch07_10' },
          { text: '7.5.5 示例：包含 ESR 的 Boost 变换器状态空间平均', link: '/power-electronics/ch07_11' },
          { text: '习题', link: '/power-electronics/ch07_12' },
        ],
      },
      {
        text: '第 8 章 变换器传递函数',
        collapsed: true,
        items: [
          { text: '章节概览', link: '/power-electronics/ch08' },
          { text: '8.1.1 单极点响应：系统带宽的守门人', link: '/power-electronics/ch08_1' },
          { text: '8.1.5 组合叠加：把积木拼成系统', link: '/power-electronics/ch08_2' },
          { text: '8.1.6 二阶极点响应：谐振', link: '/power-electronics/ch08_3' },
          { text: '8.1.7 低 Q 近似：把复根拆成实根', link: '/power-electronics/ch08_4' },
          { text: '8.1.8 高 Q 近似：阻尼源的并联', link: '/power-electronics/ch08_5' },
          { text: '8.1.9 任意次多项式的近似根', link: '/power-electronics/ch08_6' },
          { text: '8.2 变换器传递函数分析', link: '/power-electronics/ch08_7' },
          { text: '8.3 阻抗与传递函数的图形构建法', link: '/power-electronics/ch08_8' },
          { text: '8.4 图解法构建变换器传递函数', link: '/power-electronics/ch08_9' },
          { text: '8.5 交流传递函数与阻抗的实测', link: '/power-electronics/ch08_10' },
          { text: '8.11 习题：真正的试炼', link: '/power-electronics/ch08_11' },
        ],
      },
      {
        text: '第 9 章 控制器设计',
        collapsed: true,
        items: [
          { text: '章节概览', link: '/power-electronics/ch09' },
          { text: '9.1 引子：当这个世界开始变得不可控', link: '/power-electronics/ch09_1' },
          { text: '9.2 负反馈如何重塑系统的传递函数', link: '/power-electronics/ch09_2' },
          { text: '9.3 构建 1/(1+T) 和 T/(1+T)：从魔法代数到几何直觉', link: '/power-electronics/ch09_3' },
          { text: '9.4.2 奈奎斯特稳定性判据：当相位裕度失效时', link: '/power-electronics/ch09_4' },
          { text: '9.4.3 相位裕度与闭环阻尼因子：为什么裕度不够会“振铃”', link: '/power-electronics/ch09_5' },
          { text: '9.5 调节器设计：从「稳得住」到「跟得紧」', link: '/power-electronics/ch09_6' },
          { text: '9.6 测量环路增益', link: '/power-electronics/ch09_7' },
          { text: '习题：考验你的时候到了', link: '/power-electronics/ch09_8' },
        ],
      },
    ],
  },
  {
    text: '磁元件设计',
    collapsed: false,
    items: [
      {
        text: '第 10 章 磁性基础理论',
        collapsed: true,
        items: [
          { text: '章节概览', link: '/power-electronics/ch10' },
          { text: '10.1 磁学基础回顾：重建你的直觉', link: '/power-electronics/ch10_1' },
          { text: '10.2 变压器建模', link: '/power-electronics/ch10_2' },
          { text: '10.3 磁性元件里的损耗机制', link: '/power-electronics/ch10_3' },
          { text: '10.4.1 集肤效应与邻近效应：当导线不再是导线', link: '/power-electronics/ch10_4' },
          { text: '10.4.2 绕组里的漏磁通：看不见的磁场力场', link: '/power-electronics/ch10_5' },
          { text: '10.4.4 层内的功率损耗', link: '/power-electronics/ch10_6' },
          { text: '10.4.6 交错绕组', link: '/power-electronics/ch10_7' },
          { text: '10.4.7 PWM 波形谐波：不要被正弦波骗了', link: '/power-electronics/ch10_8' },
          { text: '10.5 几种磁性器件、它们的 B-H 回环以及铁损与铜损的较量', link: '/power-electronics/ch10_9' },
          { text: '10.6 关键点总结', link: '/power-electronics/ch10_10' },
          { text: '10.11 实战中的损耗计算', link: '/power-electronics/ch10_11' },
        ],
      },
      {
        text: '第 11 章 铜与铁的博弈',
        collapsed: true,
        items: [
          { text: '章节概览', link: '/power-electronics/ch11' },
          { text: '11.1 滤波电感的设计约束', link: '/power-electronics/ch11_1' },
          { text: '11.3 多绕组磁元件设计：扩展 Kg 法', link: '/power-electronics/ch11_2' },
          { text: '11.4 实战演练：两个设计案例', link: '/power-electronics/ch11_3' },
          { text: '11.5 习题：磁性元件设计', link: '/power-electronics/ch11_4' },
        ],
      },
      {
        text: '第 12 章 变压器设计：当磁芯开始发烫',
        collapsed: true,
        items: [
          { text: '章节概览', link: '/power-electronics/ch12' },
          { text: '12.1 变压器设计：基本约束', link: '/power-electronics/ch12_1' },
          { text: '12.2 变压器初步设计流程：把公式变成绕组', link: '/power-electronics/ch12_2' },
          { text: '12.3 实战演练', link: '/power-electronics/ch12_3' },
          { text: '12.4 AC 电感器设计', link: '/power-electronics/ch12_4' },
          { text: '12.5 练习题：纸上得来终觉浅', link: '/power-electronics/ch12_5' },
        ],
      },
    ],
  },
  {
    text: '面向设计的分析技术',
    collapsed: false,
    items: [
      {
        text: '第 13 章 面向设计的分析技术：反馈定理',
        collapsed: true,
        items: [
          { text: '章节概览', link: '/power-electronics/ch13' },
          { text: '13.1 当环路不再是纸上的圆圈', link: '/power-electronics/ch13_1' },
          { text: '13.2 反馈定理', link: '/power-electronics/ch13_2' },
          { text: '13.3 实例：运放 PD 补偿电路', link: '/power-electronics/ch13_3' },
          { text: '13.4 示例：闭环调节器', link: '/power-electronics/ch13_4' },
          { text: '13.5 习题', link: '/power-electronics/ch13_5' },
        ],
      },
      {
        text: '第 14 章 电路平均法与平均开关模型',
        collapsed: true,
        items: [
          { text: '章节概览', link: '/power-electronics/ch14' },
          { text: '14.1 电路平均与平均开关模型', link: '/power-electronics/ch14_1' },
          { text: '14.2 开关网络的其他配置', link: '/power-electronics/ch14_2' },
          { text: '14.3 平均电路模型的仿真', link: '/power-electronics/ch14_3' },
          { text: '14.4 习题：从推导到仿真', link: '/power-electronics/ch14_4' },
        ],
      },
      {
        text: '第 15 章 断续导通模式（DCM）的建模',
        collapsed: true,
        items: [
          { text: '章节概览', link: '/power-electronics/ch15' },
          { text: '15.1 DCM 变换器动态特性导论', link: '/power-electronics/ch15_1' },
          { text: '15.2 DCM 平均开关模型', link: '/power-electronics/ch15_2' },
          { text: '15.3 DCM 开关网络的小信号交流建模', link: '/power-electronics/ch15_3' },
          { text: '15.4 打通 CCM 和 DCM 的统一仿真模型', link: '/power-electronics/ch15_4' },
          { text: '15.5 DCM 变换器的高频动力学', link: '/power-electronics/ch15_5' },
          { text: '15.6 习题', link: '/power-electronics/ch15_6' },
        ],
      },
      {
        text: '第 16 章 额外元件定理',
        collapsed: true,
        items: [
          { text: '章节概览', link: '/power-electronics/ch16' },
          { text: '16.1 额外元件定理', link: '/power-electronics/ch16_1' },
          { text: '16.2 EET 实战演练', link: '/power-electronics/ch16_2' },
          { text: '16.3 n-多重额外元件定理', link: '/power-electronics/ch16_3' },
          { text: '16.4 n-EET 实战演练', link: '/power-electronics/ch16_4' },
          { text: '16.5 频率倒置', link: '/power-electronics/ch16_5' },
          { text: '16.6 习题：面向设计的分析综合演练', link: '/power-electronics/ch16_6' },
        ],
      },
      {
        text: '第 17 章 输入滤波器设计',
        collapsed: true,
        items: [
          { text: '章节概览', link: '/power-electronics/ch17' },
          { text: '17.1 引言', link: '/power-electronics/ch17_1' },
          { text: '17.2 输入滤波器对变换器传递函数的影响', link: '/power-electronics/ch17_2' },
          { text: '17.3 Buck 变换器实例：失控的滤波器', link: '/power-electronics/ch17_3' },
          { text: '17.4 阻尼输入滤波器的精打细算设计', link: '/power-electronics/ch17_4' },
          { text: '17.5 稳定性判据', link: '/power-electronics/ch17_5' },
          { text: '17.6 练习题：当洁净电源成为隐患', link: '/power-electronics/ch17_6' },
        ],
      },
    ],
  },
  {
    text: '闭环控制',
    collapsed: false,
    items: [
      {
        text: '第 18 章 电流编程控制（CPM）',
        collapsed: true,
        items: [
          { text: '章节概览', link: '/power-electronics/ch18' },
          { text: '18.1 简单一阶模型', link: '/power-electronics/ch18_1' },
          { text: '18.2 当 D > 0.5 时：失控的振荡与人工斜坡的救赎', link: '/power-electronics/ch18_2' },
          { text: '18.3 一个更精确的模型', link: '/power-electronics/ch18_3' },
          { text: '18.4 电流程序控制传递函数：精确推导与隐含的真相', link: '/power-electronics/ch18_4' },
          { text: '18.5 仿真模型的构建与验证', link: '/power-electronics/ch18_5' },
          { text: '18.6 电流程序控制变换器的外环电压反馈', link: '/power-electronics/ch18_6' },
          { text: '18.7 高频动力学：当模型失效时', link: '/power-electronics/ch18_7' },
          { text: '18.8 断续导通模式（DCM）', link: '/power-electronics/ch18_8' },
          { text: '18.9 平均电流模式控制', link: '/power-electronics/ch18_9' },
          { text: '18.10 核心要点回顾', link: '/power-electronics/ch18_10' },
          { text: '18.11 习题：也就是真的要上手了', link: '/power-electronics/ch18_11' },
        ],
      },
      {
        text: '第 19 章 数字控制的代价与力量',
        collapsed: true,
        items: [
          { text: '章节概览', link: '/power-electronics/ch19' },
          { text: '19.1 数字控制环路', link: '/power-electronics/ch19_1' },
          { text: '19.2 离散时间系统入门', link: '/power-electronics/ch19_2' },
          { text: '19.3 离散时间补偿器设计', link: '/power-electronics/ch19_3' },
          { text: '19.4 数字控制器的实现', link: '/power-electronics/ch19_4' },
          { text: '19.5 习题', link: '/power-electronics/ch19_5' },
        ],
      },
    ],
  },
  {
    text: '谐波、整流与软开关',
    collapsed: false,
    items: [
      {
        text: '第 20 章 非正弦系统里的功率与谐波',
        collapsed: true,
        items: [
          { text: '章节概览', link: '/power-electronics/ch20' },
          { text: '20.1 平均功率：谁在真正传输能量', link: '/power-electronics/ch20_1' },
          { text: '20.3 功率因数：真正的"性价比"', link: '/power-electronics/ch20_2' },
          { text: '20.5 三相系统里的谐波电流', link: '/power-electronics/ch20_3' },
          { text: '20.4 习题：把波形撕碎再拼回来', link: '/power-electronics/ch20_4' },
        ],
      },
      {
        text: '第 21 章 脉宽调制整流器',
        collapsed: true,
        items: [
          { text: '章节概览', link: '/power-electronics/ch21' },
          { text: '21.1 理想整流器特性', link: '/power-electronics/ch21_1' },
          { text: '21.2 近似理想整流器的实现', link: '/power-electronics/ch21_2' },
          { text: '21.3 控制电流波形', link: '/power-electronics/ch21_3' },
          { text: '21.4 单相变换器系统：集成理想整流器', link: '/power-electronics/ch21_4' },
          { text: '21.5 整流器波形的 RMS 值', link: '/power-electronics/ch21_5' },
          { text: '21.6 CCM 高质量整流器：损耗与效率建模', link: '/power-electronics/ch21_6' },
          { text: '21.7 理想三相整流器', link: '/power-electronics/ch21_7' },
          { text: '21.8 知识点复盘与回扣', link: '/power-electronics/ch21_8' },
          { text: '21.9 实战演练与习题', link: '/power-electronics/ch21_9' },
        ],
      },
      {
        text: '第 22 章 谐振变换',
        collapsed: true,
        items: [
          { text: '章节概览', link: '/power-electronics/ch22' },
          { text: '22.1 正弦近似：化繁为简的魔术', link: '/power-electronics/ch22_1' },
          { text: '22.2 示例演练', link: '/power-electronics/ch22_2' },
          { text: '22.3 软开关技术', link: '/power-electronics/ch22_3' },
          { text: '22.4.1 逆变器的输出特性', link: '/power-electronics/ch22_4' },
          { text: '22.4.2 晶体管电流对负载的依赖', link: '/power-electronics/ch22_5' },
          { text: '22.4.3 ZVS/ZCS 边界对负载电阻的依赖', link: '/power-electronics/ch22_6' },
          { text: '22.4.4 从指标回到槽路', link: '/power-electronics/ch22_7' },
          { text: '22.4.5 LLC 变换器实例', link: '/power-electronics/ch22_8' },
          { text: '22.5 串联和并联谐振变换器的精确特性', link: '/power-electronics/ch22_9' },
          { text: '22.10 问题与实战', link: '/power-electronics/ch22_10' },
        ],
      },
      {
        text: '第 23 章 软开关技术',
        collapsed: true,
        items: [
          { text: '章节概览', link: '/power-electronics/ch23' },
          { text: '23.1 半导体器件的软开关机理', link: '/power-electronics/ch23_1' },
          { text: '23.2 零电流开关（ZCS）准谐振开关单元', link: '/power-electronics/ch23_2' },
          { text: '23.3 谐振开关拓扑', link: '/power-electronics/ch23_3' },
          { text: '23.4 PWM 变换器中的软开关技术', link: '/power-electronics/ch23_4' },
          { text: '23.5 关键要点总结', link: '/power-electronics/ch23_5' },
          { text: '23.6 习题：软开关综合练习', link: '/power-electronics/ch23_6' },
        ],
      },
    ],
  },
]
